export const MODULES = [
  {
    id: 'fee-engine',
    label: 'Fee Engine',
    route: '/manage',
    icon: 'receipt',
    permissions: ['can_view_quotes'],
    status: 'live',
    group: 'billing',
    children: [
      { id: 'fe-dashboard', label: 'Dashboard', route: '/manage' },
      { id: 'fe-new-quote', label: 'New Quote', route: '/manage/quotes/new' },
      { id: 'fe-clients', label: 'Clients', route: '/manage/clients' },
      { id: 'fe-quotes', label: 'Quotes', route: '/manage/quotes' },
      { id: 'fe-groups', label: 'Groups', route: '/manage/groups' },
      { id: 'fe-billing', label: 'Billing Review', route: '/manage/billing' },
      { id: 'fe-pricing', label: 'Pricing', route: '/manage/quotes/pricing', permissions: ['can_edit_fee_schedule'] },
    ],
  },
  {
    id: 'billing',
    label: 'Billing',
    route: '/billing',
    icon: 'file-text',
    permissions: ['can_view_billing'],
    status: 'live',
    group: 'billing',
  },
  {
    id: 'clients',
    label: 'Clients',
    route: '/clients',
    icon: 'users',
    permissions: [],
    status: 'live',
    group: 'billing',
  },
  {
    id: 'onboarding',
    label: 'Onboarding',
    route: '/onboarding',
    icon: 'user-plus',
    permissions: ['can_view_onboarding'],
    status: 'live',
    group: 'billing',
  },
  {
    id: 'communications',
    label: 'Communications',
    route: '/comms',
    icon: 'inbox',
    permissions: [],
    status: 'live',
    group: 'billing',
    children: [
      { id: 'comms-email', label: 'Email', route: '/comms/email' },
      { id: 'comms-sms', label: 'Text Messages', route: '/comms/sms' },
      { id: 'comms-whatsapp', label: 'WhatsApp', route: '/comms/whatsapp' },
      { id: 'comms-reminders', label: 'Client Tax Reminders', route: '/comms/reminders' },
      { id: 'comms-preferences', label: 'Client Preferences', route: '/comms/preferences' },
    ],
  },
  {
    id: 'work-planner',
    label: 'Work',
    route: '/planner',
    icon: 'clock',
    permissions: ['work_planner'],
    status: 'live',
    group: 'team',
    children: [
      {
        id: 'wp-task',
        label: 'Planner',
        route: '/planner/ready',
        matchPaths: ['/planner', '/planner/ready', '/planner/waiting', '/planner/quick', '/planner/scheduled', '/planner/calendar', '/planner/kanban', '/planner/completed'],
      },
      {
        id: 'wp-capacity',
        label: 'Capacity',
        route: '/planner/allocations',
        matchPaths: ['/planner/allocations', '/planner/estimates', '/planner/capacity'],
      },
      {
        id: 'wp-job-review',
        label: 'Job Review',
        route: '/planner/review',
        matchPaths: ['/planner/review', '/planner/review/team'],
      },
      {
        id: 'wp-timesheets',
        label: 'Timesheets',
        route: '/timesheets',
        permissions: ['can_view_timesheets'],
        matchPaths: ['/timesheets'],
      },
      { id: 'wp-triage', label: 'Triage Board', route: '/triage' },
    ],
  },
  {
    id: 'client-work',
    label: 'Client Work',
    route: '/client-dashboard',
    icon: 'briefcase',
    permissions: [],
    status: 'live',
    group: 'data',
    children: [
      { id: 'cw-dashboard', label: 'Client Dashboard', route: '/client-dashboard', permissions: ['can_view_reports'] },
      { id: 'cw-portfolio', label: 'Portfolio', route: '/portfolio', permissions: ['can_view_reports'] },
      { id: 'cw-reports', label: 'Client Reports', route: '/reports', permissions: ['can_view_reports'] },
      { id: 'cw-forecast', label: 'Client Forecast', route: '/forecast', permissions: ['can_manage_portal'] },
    ],
  },
  {
    id: 'planning',
    label: 'Practice Planning',
    route: '/planning',
    icon: 'trending-up',
    permissions: ['can_manage_portal'],
    status: 'live',
    group: 'data',
  },
  {
    id: 'pd-tracker',
    label: 'CPD Tracker',
    route: '/team/pd',
    icon: 'graduation-cap',
    permissions: ['can_view_pd_tracker'],
    status: 'live',
    group: 'team',
  },
  {
    id: 'recruitment',
    label: 'Recruitment',
    route: '/recruitment',
    icon: 'user-check',
    permissions: ['can_view_recruitment'],
    status: 'live',
    group: 'team',
    children: [
      { id: 'rec-vacancies', label: 'Vacancies', route: '/recruitment', matchPaths: ['/recruitment'] },
      { id: 'rec-interviews', label: 'Interviews', route: '/recruitment/interviews', matchPaths: ['/recruitment/interviews'] },
    ],
  },
  {
    id: 'bugs',
    label: 'Bug Reports',
    route: '/bugs',
    icon: 'bug',
    permissions: [],
    status: 'live',
    group: 'meta',
  },
  {
    id: 'issues',
    label: 'Issues Log',
    route: '/issues',
    icon: 'alert-triangle',
    permissions: [],
    status: 'live',
    group: 'meta',
  },
  {
    id: 'ideas',
    label: 'Ideas',
    route: '/ideas',
    icon: 'lightbulb',
    permissions: [],
    status: 'live',
    group: 'meta',
  },
];
