export const MODULES = [
  {
    id: 'fee-engine',
    label: 'Fee Engine',
    route: '/manage',
    icon: 'receipt',
    permissions: ['can_view_quotes'],
    status: 'live',
    group: 'billing',
  },
  {
    id: 'reports',
    label: 'Reports',
    route: '/manage/quotes/analysis',
    icon: 'bar-chart-2',
    permissions: ['can_view_reports'],
    status: 'live',
    group: 'data',
  },
  {
    id: 'work-planner',
    label: 'Work planner',
    route: '/team/work',
    icon: 'clock',
    permissions: ['can_view_work_planner'],
    status: 'planned',
    group: 'team',
  },
  {
    id: 'pd-tracker',
    label: 'PD tracker',
    route: '/team/pd',
    icon: 'graduation-cap',
    permissions: ['can_view_pd_tracker'],
    status: 'planned',
    group: 'team',
  },
  {
    id: 'ideas',
    label: 'Ideas',
    route: '/ideas',
    icon: 'lightbulb',
    permissions: [],
    status: 'live',
    group: 'meta',
  },
];
